import os

__author__ = "Kristina Sungeun Song"
__email__ = "kristina.song@usherbrooke.ca"

configfile: "config/config.yaml"

#############################
## Samples Information
#############################

SAMPLES = config["samples"]
READS = ["R1","R2"]


#############################
## Load rules
#############################

include: "rules/trim.smk"
include: "rules/fastqc.smk"
include: "rules/align.smk"
#include: "rules/quantification.smk"
#include: "rules/diffexp.smk"

#############################
## Target rules
#############################

rule all:
    input:
        fastqc = expand("results/fastqc/{step}/{sample}_{read}_fastqc.{ext}", sample=SAMPLES, read=READS, step=["pretrim","posttrim"], ext=["html","zip"]),
        star = expand("results/star/{sample}/{sample}_Aligned.sortedByCoord.out.bam", sample=SAMPLES)
