import os

__author__ = "Kristina Sungeun Song"
__email__ = "kristina.song@usherbrooke.ca"

configfile: "config/config.yaml"

#############################
## Samples Information
#############################

SAMPLES = config["samples"]
READS = ["R1","R2"]


#############################
## Load rules
#############################

include: "rules/trim.smk"
include: "rules/fastqc.smk"
include: "rules/align.smk"
include: "rules/quantification.smk"
#include: "rules/diffexp.smk"

#############################
## Target rules
#############################

rule all:
    input:
        expand("results/fastqc/pretrim/{sample}_{read}.html", sample=SAMPLES, read=READS),
        expand("results/fastqc/posttrim/{sample}_{read}.html", sample=SAMPLES, read=READS),
        expand("results/genomecov/{sample}.bedgraph", sample=SAMPLES),
        expand("results/kallisto/{sample}", sample=SAMPLES)