__default__:
  account: def-scottmic
  mail-user: kristina.song@usherbrooke.ca
  mail-type: FAIL
  job-name: "smk_{rule}_{wildcards}"
  time: 180 # minutes
  nodes: 1
  ntasks: 1
  mem: 32000M
  cpus-per-task: 16
  output: results/logs/slurmout/{rule}.{wildcards}.out
  error: results/logs/slurmout/{rule}.{wildcards}.err

fastqc_pretrim:
  time: 30

pretrim_fname:
  time: 30

fastqc_posttrim_R1:
  time: 30

fastqc_posttrim_R2:
  time: 30

star_index:
  mem: 128000M
  cpus-per-task: 32

star_align:
  mem: 128000M
  cpus-per-task: 32

primary_alignments:
  mem: 4000M
  time: 120
  cpus-per-task: 1

genomecov:
  mem: 8000M
  cpus-per-task: 1

kallisto_index:
  mem: 128000M
  cpus-per-task: 32

kallisto_quant:
  mem: 128000M
  cpus-per-task: 32

picard:
  time: 30