__default__:
  account: def-sabou
  mail-user: kristina.song@usherbrooke.ca
  mail-type: FAIL
  job-name: "smk_{rule}_{wildcards}"
  time: 180 # minutes
  nodes: 1
  ntasks: 1
  mem: 32000M
  cpus-per-task: 16
  output: results/logs/slurmout/{rule}.{wildcards}.out
  error: results/logs/slurmout/{rule}.{wildcards}.err


star_index:
  mem: 128000M
  cpus-per-task: 32

star_align:
  mem: 128000M
  cpus-per-task: 32
  time: 600

kallisto_quant:
  time: 600

rmats_paired:
  time: 1440

trimmomatic:
  time: 1440
