samples: ["NC5_n2_S6","NC5_n3_S1","22_1_n1_S2","22_2_n1_S3","22_1_n2_S7","22_2_n2_S8"]
#samples: ["NC5_n2_S6","NC5_n3_S1","48_1_n1_S4","48_2_n1_S5","48_1_n3_S2","48_2_n3_S3"]

snoRNA: ["ENSG00000277194"]
#snoRNA: ["ENSG00000201823"]

path:
  fastq: "data/samples"
  genome_fasta: "data/references/Homo_sapiens.GRCh38.dna.primary_assembly_V101.fa"
  genome_gtf: "data/references/hg38_Ensembl_V101_Scottlab_2020.gtf"
  genome_tsv: "data/references/hg38_Ensembl_V101_Scottlab_2020.tsv"
  transcriptome: "data/references/transcriptome.fa"
  gff3: "data/references/hg38_Ensembl_V101_Scottlab_2020.gff3"
  sno_interactions: "data/sno_interactions"

params:
  trimmomatic: "ILLUMINACLIP:data/Adapters-PE_NextSeq.fa:2:12:10:8:true TRAILING:30 LEADING:30 MINLEN:3"
  star: "--outFilterScoreMinOverLread 0.3 --outFilterMatchNminOverLread 0.3 --outFilterMultimapNmax 100 --winAnchorMultimapNmax 100 --alignEndsProtrude 5 ConcordantPair"
  picard: "--MINIMUM_PCT 0.5"

tools:
  majiq_voila: "/home/kris98/scratch/RNAseq/workflow/envs/majiq_voila/bin/activate"