samples: ['SKOV_SNORD22_OVE_N1','SKOV_SNORD22_OVE_N2','SKOV_SNORD22_OVE_N4','SKOV_pcDNA3-1_N1','SKOV_pcDNA3-1_N2','SKOV_pcDNA3-1_N4']

path:
  genome_fasta: "/home/kris98/projects/def-scottmic/kris98/annotation_datasets/Homo_sapiens.GRCh38.110.dna.primary_assembly.fa"
  genome_gtf: "/home/kris98/projects/def-scottmic/kris98/annotation_datasets/Homo_sapiens.GRCh38.110_snoRNAs_tRNAs.gtf"

params:
  readlength: 80 # for rMATS
