samples: ["SNORA81_EmptyPlasmid_1_S1","SNORA81_EmptyPlasmid_2_S3","SNORA81_EmptyPlasmid_3_S5","SNORD22_OVEPlasmid_1_S2","SNORD22_OVEPlasmid_2_S4","SNORD22_OVEPlasmid_3_S6"]

path:
  genome_fasta: "/home/kris98/projects/def-scottmic/kris98/annotation_datasets/Homo_sapiens.GRCh38.110.dna.primary_assembly.fa"
  genome_gtf: "/home/kris98/projects/def-scottmic/kris98/annotation_datasets/Homo_sapiens.GRCh38.110_snoRNAs_tRNAs.gtf"

params:
  readlength: 80 # for rMATS

tools:
  majiq_voila: "/home/kris98/scratch/RNAseq/workflow/envs/majiq_voila/bin/activate"